name: Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: master

    - run: zig build run-sample
    - run: zig build test
    - run: zig build
 